# Generated by Django 4.1.7 on 2023-04-07 08:17

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=core.models.generate_user_id,
                        editable=False,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=700, null=True)),
                ("last_name", models.CharField(blank=True, max_length=700, null=True)),
                ("mobile_number", models.CharField(max_length=15)),
                ("is_mobile_number_verified", models.BooleanField(default=False)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("dob", models.DateField(null=True)),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.get_profile_photo_filepath_with_name,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="SuperUser"),
                ),
                ("ratings", models.IntegerField(default=2)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_name",
                    models.CharField(
                        choices=[(2, "MOBILE"), (1, "EMAIL")], max_length=15
                    ),
                ),
                ("key_value", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=33)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line1", models.CharField(max_length=300)),
                ("line2", models.CharField(blank=True, max_length=300, null=True)),
                ("city", models.CharField(default="MUMBAI", max_length=200)),
                ("state", models.CharField(default="MAHARASHTRA", max_length=200)),
                ("country", models.CharField(default="INDIA", max_length=200)),
                ("landmark", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
