# Generated by Django 4.1.7 on 2023-04-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Staff"),
        ),
    ]
