# Generated by Django 4.1.7 on 2023-04-07 19:14

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(
                        default=core.models.generate_user_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLOTH", "Cloth"),
                            ("ELECTRONIC", "Electronic"),
                            ("FOOTWEAR", "FootWear"),
                            ("ACCESSORIES", "Accesssories"),
                        ],
                        default="CLOTH",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.get_product_photo_filepath_with_name,
                    ),
                ),
                ("ratings", models.IntegerField(default=2)),
                ("is_available", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_product",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[(2, "Accept"), (3, "Reject"), (1, "Pending")],
                        default=1,
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_date",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True
                    ),
                ),
                (
                    "updated_date",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True
                    ),
                ),
                (
                    "receiver_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
