# Generated by Django 4.1.7 on 2023-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_product_friendrequestmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_price",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
