# Generated by Django 4.1.7 on 2023-04-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_product_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product_price",
            new_name="price",
        ),
    ]
